# -*- coding: utf-8 -*-
"""Untitled8Create a Python Streamlit BMI Calculator Web App in Just 6 Minutes, provide Google Colab URL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqEQl6Nw3_wbXc39HskdRiiFrMLmwuMS
"""

# Commented out IPython magic to ensure Python compatibility.
# !pip install streamlit
# !pip install pyngrok
# 
# %%writefile app.py
# import streamlit as st
# 
# def bmi_calculator():
#     st.title("BMI Calculator")
# 
#     weight = st.number_input("Enter your weight (kg)", min_value=1.0, format="%.2f")
#     height = st.number_input("Enter your height (m)", min_value=0.5, format="%.2f")
# 
#     if st.button("Calculate BMI"):
#         bmi = weight / (height ** 2)
#         st.write(f"### Your BMI: {bmi:.2f}")
# 
#         if bmi < 18.5:
#             st.warning("You are underweight.")
#         elif 18.5 <= bmi < 24.9:
#             st.success("You have a normal weight.")
#         elif 25 <= bmi < 29.9:
#             st.warning("You are overweight.")
#         else:
#             st.error("You are obese.")
# 
# if __name__ == "__main__":
#     bmi_calculator()
#

