# -*- coding: utf-8 -*-
"""Untitled Build a Python Website in 15 Minutes With Streamlit, provide Google Colab URL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSEPn4j23qYbCgON7GZUVd1GFvigS-i1
"""

# Commented out IPython magic to ensure Python compatibility.
# !pip install streamlit
# !pip install pyngrok
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# # Website Title
# st.title("🌍 My First Streamlit Website")
# 
# # Sidebar
# st.sidebar.header("Navigation")
# page = st.sidebar.radio("Go to", ["Home", "About", "Data Visualization"])
# 
# # Home Page
# if page == "Home":
#     st.header("Welcome to My Streamlit Website! 🎉")
#     st.write("This is a simple Python web app built with **Streamlit**.")
#     st.image("https://source.unsplash.com/800x400/?technology,web")
# 
#     # User Input Form
#     st.subheader("Let's Get to Know You!")
#     name = st.text_input("Enter your name:")
#     if name:
#         st.write(f"Hello, **{name}**! 👋")
# 
# # About Page
# elif page == "About":
#     st.header("About This Website")
#     st.write("This website is built using **Python & Streamlit** in just 15 minutes!")
# 
# # Data Visualization Page
# elif page == "Data Visualization":
#     st.header("📊 Simple Data Visualization")
# 
#     # Create a simple DataFrame
#     data = pd.DataFrame({
#         "Category": ["A", "B", "C", "D"],
#         "Values": [10, 30, 20, 40]
#     })
# 
#     # Plot the data
#     fig, ax = plt.subplots()
#     ax.bar(data["Category"], data["Values"], color=['red', 'blue', 'green', 'orange'])
#     st.pyplot(fig)
# 
# st.sidebar.info("Developed with ❤️ using Python & Streamlit")
# from pyngrok import ngrok
# 
# # Start Streamlit in the background
# !streamlit run app.py &
# 
# # Generate a public URL using ngrok
# public_url = ngrok.connect(8501)
# print("Your Streamlit app is running at:", public_url)
#

